import { orderBy, where, deleteField } from "firebase/firestore";
import type { Emi, EmiType, ScheduleStatus, Transaction } from "@/types";
import { monthKeyFromISODate, occurrenceAt, todayISODate } from "@/lib/date";
import { emiInstallmentTxnId } from "@/lib/derive";
import {
  COLLECTIONS,
  createDoc,
  deleteDocById,
  listDocs,
  setDocById,
  updateDocById,
} from "./firestore";

const NAME = COLLECTIONS.emis;

export type EmiInput = {
  name: string;
  emiType: EmiType;
  monthlyAmount: number;
  startDate: string;
  months: number;
  categoryId?: string;
  creditCardId?: string;
  accountId?: string;
  paymentMethodId?: string;
  note?: string;
};

/** Last installment date for a plan = occurrence (months - 1). */
export function emiEndDate(startDate: string, months: number): string {
  return occurrenceAt(startDate, "monthly", Math.max(0, months - 1));
}

export function listEmis(uid: string): Promise<Emi[]> {
  return listDocs<Emi>(uid, NAME, orderBy("startDate", "desc"));
}

export function createEmi(uid: string, input: EmiInput): Promise<string> {
  return createDoc<Emi>(uid, NAME, {
    ...input,
    endDate: emiEndDate(input.startDate, input.months),
    status: "active" as ScheduleStatus,
  });
}

/**
 * Update an EMI. When the schedule shape changes, callers must pass BOTH
 * `startDate` and `months` (the form always does) so the stored `endDate`
 * stays consistent.
 */
/** Optional fields an edit can clear by passing them explicitly as undefined. */
const CLEARABLE_EMI_FIELDS = [
  "categoryId",
  "creditCardId",
  "accountId",
  "paymentMethodId",
  "note",
] as const;

export function updateEmi(
  uid: string,
  id: string,
  patch: Partial<EmiInput & { status: ScheduleStatus; lastGeneratedThrough: string }>,
): Promise<void> {
  const next: Record<string, unknown> = { ...patch };
  if (patch.startDate !== undefined && patch.months !== undefined) {
    next.endDate = emiEndDate(patch.startDate, patch.months);
  }
  for (const key of CLEARABLE_EMI_FIELDS) {
    if (key in patch && patch[key] === undefined) next[key] = deleteField();
  }
  return updateDocById<Emi>(uid, NAME, id, next as Partial<Emi>);
}

/** Pause: engine skips it. Resume: skip the paused window (no backfill). */
export const pauseEmi = (uid: string, id: string) =>
  updateDocById<Emi>(uid, NAME, id, { status: "paused" });
export const resumeEmi = (uid: string, id: string) =>
  updateDocById<Emi>(uid, NAME, id, {
    status: "active",
    lastGeneratedThrough: todayISODate(),
  });
export const stopEmi = (uid: string, id: string) =>
  updateDocById<Emi>(uid, NAME, id, { status: "stopped" });

export const deleteEmi = (uid: string, id: string) => deleteDocById(uid, NAME, id);

/**
 * Installment transactions recorded for one EMI, newest first.
 * Requires the composite index (emiId ASC, date DESC).
 */
export function listEmiTransactions(uid: string, emiId: string): Promise<Transaction[]> {
  return listDocs<Transaction>(
    uid,
    COLLECTIONS.transactions,
    where("emiId", "==", emiId),
    orderBy("date", "desc"),
  );
}

export interface MarkInstallmentInput {
  /** Scheduled occurrence date of the slot being paid — fixes the slot id. */
  scheduledDate: string;
  /** Actual date the user paid (drives month attribution). */
  payDate: string;
  amount: number;
  accountId?: string;
  creditCardId?: string;
  paymentMethodId?: string;
}

/**
 * Record an EMI installment as paid: upsert a tagged expense transaction at the
 * slot's deterministic id. Idempotent per slot (re-marking overwrites). The
 * `emiId` tag makes it count as EMI everywhere; the funding source (account or
 * card) flows it into Net Cash / card outstanding like any other expense.
 */
export function markInstallmentPaid(
  uid: string,
  emi: Emi,
  input: MarkInstallmentInput,
): Promise<void> {
  const data: Record<string, unknown> = {
    type: "expense",
    date: input.payDate,
    monthKey: monthKeyFromISODate(input.payDate),
    amount: input.amount,
    merchant: emi.name,
    emiId: emi.id,
    isAutoGenerated: false,
  };
  // Only set optional links when present — Firestore rejects `undefined`.
  if (emi.categoryId) data.categoryId = emi.categoryId;
  if (input.accountId) data.accountId = input.accountId;
  if (input.creditCardId) data.creditCardId = input.creditCardId;
  if (input.paymentMethodId) data.paymentMethodId = input.paymentMethodId;
  if (emi.note) data.note = emi.note;
  return setDocById<Transaction>(
    uid,
    COLLECTIONS.transactions,
    emiInstallmentTxnId(emi.id, input.scheduledDate),
    data as Omit<Transaction, "id" | "createdAt" | "updatedAt">,
  );
}

/** Undo a recorded installment — deletes that slot's transaction. */
export function markInstallmentUnpaid(
  uid: string,
  emiId: string,
  scheduledDate: string,
): Promise<void> {
  return deleteDocById(uid, COLLECTIONS.transactions, emiInstallmentTxnId(emiId, scheduledDate));
}
