import { writeBatch, doc, serverTimestamp } from "firebase/firestore";
import {
  differenceInCalendarDays,
  differenceInCalendarMonths,
  parseISO,
} from "date-fns";
import { db } from "@/lib/firebase";
import type { Emi, Frequency, RecurringRule } from "@/types";
import { occurrenceAt, todayISODate, monthKeyFromISODate } from "@/lib/date";
import { COLLECTIONS } from "./firestore";
import { listRecurringRules } from "./recurring";
import { listEmis, emiEndDate } from "./emis";

/**
 * The recurring engine. Materialises due occurrences of recurring rules and
 * EMI plans as real transaction documents.
 *
 * Correctness properties:
 * - IDEMPOTENT: generated transactions use deterministic doc ids
 *   (`rec-{ruleId}-{date}`, `emi-{emiId}-{date}`), so re-running — even from
 *   two tabs racing — writes the same docs instead of duplicating them.
 * - ATOMIC: each batch commits the generated transactions TOGETHER with the
 *   source's `lastGeneratedThrough` bookkeeping, so a partial failure can
 *   never skip occurrences or double-advance.
 * - PAUSE-AWARE: paused sources are skipped and `lastGeneratedThrough` is NOT
 *   advanced; the resume action fast-forwards it so paused periods are never
 *   backfilled.
 */

/** Hard cap per source per run — backstop against runaway schedules. */
const MAX_OCCURRENCES_PER_RUN = 730; // ~2 years of a daily rule
/** Firestore batch limit is 500 writes; leave room for bookkeeping. */
const BATCH_SIZE = 400;

/**
 * Index of the first occurrence that could fall after `lowerBoundISO` —
 * computed arithmetically so ancient schedules don't require iterating from
 * k=0 (a years-old daily rule would otherwise exhaust any loop cap before
 * reaching the current window). Steps back one index to absorb clamping.
 */
function firstCandidateIndex(
  startISO: string,
  frequency: Frequency,
  lowerBoundISO: string | undefined,
): number {
  if (!lowerBoundISO) return 0;
  const start = parseISO(startISO);
  const lb = parseISO(lowerBoundISO);
  let k: number;
  switch (frequency) {
    case "daily":
      k = differenceInCalendarDays(lb, start);
      break;
    case "weekly":
      k = Math.floor(differenceInCalendarDays(lb, start) / 7);
      break;
    case "monthly":
      k = differenceInCalendarMonths(lb, start);
      break;
    case "quarterly":
      k = Math.floor(differenceInCalendarMonths(lb, start) / 3);
      break;
    case "yearly":
      k = Math.floor(differenceInCalendarMonths(lb, start) / 12);
      break;
  }
  return Math.max(0, k - 1);
}

/**
 * All occurrence dates of a schedule in (`afterISO`, `untilISO`], capped.
 * Pure and exhaustively unit-testable.
 */
export function occurrencesBetween(
  startISO: string,
  frequency: Frequency,
  afterISO: string | undefined,
  untilISO: string,
  endISO?: string,
): string[] {
  const out: string[] = [];
  const lowerBound = afterISO ?? "";
  let k = firstCandidateIndex(startISO, frequency, afterISO);
  // Iteration guard: window size + slack for the step-back above.
  for (let i = 0; i < MAX_OCCURRENCES_PER_RUN + 4; i++, k++) {
    const occ = occurrenceAt(startISO, frequency, k);
    if (occ > untilISO) break;
    if (endISO && occ > endISO) break;
    if (occ > lowerBound) out.push(occ);
    if (out.length >= MAX_OCCURRENCES_PER_RUN) break;
  }
  return out;
}

interface GeneratedTxn {
  id: string;
  data: Record<string, unknown>;
}

function txnFromRule(rule: RecurringRule, dateISO: string): GeneratedTxn {
  return {
    id: `rec-${rule.id}-${dateISO}`,
    data: stripUndefined({
      date: dateISO,
      monthKey: monthKeyFromISODate(dateISO),
      amount: rule.amount,
      type: rule.type,
      categoryId: rule.type === "expense" ? rule.categoryId : undefined,
      incomeSourceId: rule.type === "income" ? rule.incomeSourceId : undefined,
      paymentMethodId: rule.paymentMethodId,
      creditCardId: rule.creditCardId,
      merchant: rule.merchant ?? rule.name,
      note: rule.note,
      recurringRuleId: rule.id,
      isAutoGenerated: true,
    }),
  };
}

function txnFromEmi(emi: Emi, dateISO: string): GeneratedTxn {
  return {
    id: `emi-${emi.id}-${dateISO}`,
    data: stripUndefined({
      date: dateISO,
      monthKey: monthKeyFromISODate(dateISO),
      amount: emi.monthlyAmount,
      type: "expense",
      categoryId: emi.categoryId,
      paymentMethodId: emi.paymentMethodId,
      creditCardId: emi.creditCardId,
      merchant: emi.name,
      note: emi.note,
      emiId: emi.id,
      isAutoGenerated: true,
    }),
  };
}

function stripUndefined<T extends Record<string, unknown>>(obj: T): T {
  return Object.fromEntries(
    Object.entries(obj).filter(([, v]) => v !== undefined),
  ) as T;
}

interface SourcePlan {
  collection: string;
  sourceId: string;
  txns: GeneratedTxn[];
}

/**
 * Run the engine for a user. Returns the number of transactions generated.
 * Designed to be called once per session on app load (and after creating a
 * rule/EMI so backfill appears immediately).
 */
export async function runRecurringEngine(uid: string): Promise<number> {
  const today = todayISODate();
  const [rules, emis] = await Promise.all([listRecurringRules(uid), listEmis(uid)]);

  const plans: SourcePlan[] = [];

  for (const rule of rules) {
    if (rule.status !== "active") continue;
    const due = occurrencesBetween(
      rule.startDate,
      rule.frequency,
      rule.lastGeneratedThrough,
      today,
      rule.endDate,
    );
    if (due.length) {
      plans.push({
        collection: COLLECTIONS.recurringRules,
        sourceId: rule.id,
        txns: due.map((d) => txnFromRule(rule, d)),
      });
    }
  }

  for (const emi of emis) {
    if (emi.status !== "active") continue;
    const end = emi.endDate || emiEndDate(emi.startDate, emi.months);
    const due = occurrencesBetween(
      emi.startDate,
      "monthly",
      emi.lastGeneratedThrough,
      today,
      end,
    );
    if (due.length) {
      plans.push({
        collection: COLLECTIONS.emis,
        sourceId: emi.id,
        txns: due.map((d) => txnFromEmi(emi, d)),
      });
    }
  }

  let generated = 0;
  for (const plan of plans) {
    // Chunk long backfills; each chunk advances bookkeeping atomically with
    // the transactions it writes.
    for (let i = 0; i < plan.txns.length; i += BATCH_SIZE) {
      const chunk = plan.txns.slice(i, i + BATCH_SIZE);
      const batch = writeBatch(db);
      for (const t of chunk) {
        batch.set(doc(db, "users", uid, COLLECTIONS.transactions, t.id), {
          ...t.data,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }
      const lastDate = chunk[chunk.length - 1].data.date as string;
      batch.update(doc(db, "users", uid, plan.collection, plan.sourceId), {
        lastGeneratedThrough: lastDate,
        updatedAt: serverTimestamp(),
      });
      await batch.commit();
      generated += chunk.length;
    }
  }

  return generated;
}
