import type { Timestamp } from "firebase/firestore";

/**
 * Domain models for the finance app.
 *
 * Design rule: we NEVER persist computed totals (spent, remaining, running
 * total, total invested). Those are always derived from `Transaction`,
 * `EmergencyFund` and `SipInvestment` documents at read time. Only the raw
 * source records and the *plans* (budgets) are stored.
 *
 * All collections live under `users/{uid}/...` so every user's data is isolated.
 */

/** `YYYY-MM`, e.g. "2026-06". Primary index for month/year reporting. */
export type MonthKey = string;

export type TransactionType = "expense" | "income";
export type CategoryType = "expense" | "income";
export type SipKind = "mutual_fund" | "stock" | "custom";
export type ThemePreference = "light" | "dark" | "system";
export type AccentColor = "green" | "blue" | "purple" | "orange";
export type Density = "comfortable" | "compact";
export type PaymentMethodKind = "cash" | "upi" | "bank" | "credit_card" | "other";
export type EmiType =
  | "credit_card"
  | "personal_loan"
  | "car_loan"
  | "home_loan"
  | "custom";
export type Frequency = "daily" | "weekly" | "monthly" | "quarterly" | "yearly";
/** Lifecycle of anything the recurring engine generates from. */
export type ScheduleStatus = "active" | "paused" | "stopped";

/** Base fields every Firestore document carries. */
export interface BaseDoc {
  id: string;
  createdAt: Timestamp | null;
  updatedAt: Timestamp | null;
}

export interface Category extends BaseDoc {
  name: string;
  type: CategoryType;
  /** Manual sort order (lower = first). */
  order: number;
  archived: boolean;
  color?: string;
  icon?: string;
  /**
   * Whether to show the "safe daily spend" pacing for this category (days left
   * in month + remaining ÷ days left). Defaults to true when undefined.
   */
  trackDailyPace?: boolean;
}

export interface PaymentMethod extends BaseDoc {
  name: string;
  order: number;
  archived: boolean;
  /**
   * What kind of instrument this is. Optional for backwards compatibility —
   * when missing, `resolvePaymentMethodKind` falls back to a name heuristic
   * (e.g. "Credit Card" → credit_card) so no data migration is required.
   */
  kind?: PaymentMethodKind;
}

export interface CreditCard extends BaseDoc {
  name: string; // e.g. card product name
  bankName: string;
  last4: string;
  creditLimit: number;
  /** Day of month (1-31) the statement is generated. Clamped to month length. */
  billingDay: number;
  /** Day of month (1-31) payment is due. */
  dueDay: number;
  color?: string;
  order: number;
  archived: boolean;
}

/** An EMI plan. Installment transactions are generated by the recurring engine. */
export interface Emi extends BaseDoc {
  name: string;
  emiType: EmiType;
  monthlyAmount: number;
  /** Date of the first installment, `YYYY-MM-DD`. */
  startDate: string;
  /** Total number of monthly installments. */
  months: number;
  /** Date of the last installment (start + months - 1), stored for display/query. */
  endDate: string;
  /** Category the generated installment expenses are filed under. */
  categoryId?: string;
  creditCardId?: string;
  paymentMethodId?: string;
  note?: string;
  status: ScheduleStatus;
  /** Engine bookkeeping: installments generated up to and including this date. */
  lastGeneratedThrough?: string;
}

/** A recurring transaction rule. The engine materialises occurrences as transactions. */
export interface RecurringRule extends BaseDoc {
  name: string; // e.g. "Rent", streaming subscription
  amount: number;
  type: TransactionType;
  frequency: Frequency;
  startDate: string;
  /** Optional last date — open-ended when missing. */
  endDate?: string;
  categoryId?: string;
  incomeSourceId?: string;
  paymentMethodId?: string;
  creditCardId?: string;
  merchant?: string;
  note?: string;
  status: ScheduleStatus;
  /** Engine bookkeeping: occurrences generated up to and including this date. */
  lastGeneratedThrough?: string;
}

export interface IncomeSource extends BaseDoc {
  name: string;
  order: number;
  archived: boolean;
}

/** The monthly *plan* for one expense category. Actuals come from transactions. */
export interface Budget extends BaseDoc {
  monthKey: MonthKey;
  categoryId: string;
  amount: number;
}

/** The single source of truth for actual money movement. */
export interface Transaction extends BaseDoc {
  /** ISO date string `YYYY-MM-DD`. */
  date: string;
  monthKey: MonthKey;
  amount: number;
  type: TransactionType;
  /** Expense → categoryId set. Income → incomeSourceId set. */
  categoryId?: string;
  incomeSourceId?: string;
  paymentMethodId?: string;
  /** Set when paid by credit card. */
  creditCardId?: string;
  /** Set when this transaction is an EMI installment. EMI-ness is derived from this. */
  emiId?: string;
  /** Set when materialised from a recurring rule. */
  recurringRuleId?: string;
  /** True for engine-generated transactions. */
  isAutoGenerated?: boolean;
  merchant?: string;
  note?: string;
}

export interface EmergencyFund extends BaseDoc {
  monthKey: MonthKey;
  planned: number;
  actual: number;
  note?: string;
}

export interface SipInvestment extends BaseDoc {
  monthKey: MonthKey;
  planned: number;
  actual: number;
  kind: SipKind;
  /** Fund / stock / custom instrument name. */
  name: string;
  note?: string;
}

export interface UserSettings {
  currency: string; // ISO 4217, e.g. "INR"
  locale: string; // e.g. "en-IN"
  theme: ThemePreference;
  /** 1-12, month the financial year starts (India default = 4 / April). */
  financialYearStartMonth: number;
  /** An expense at or above this amount is classified as a "large expense". */
  largeExpenseThreshold: number;
  accentColor: AccentColor;
  density: Density;
  /** Route to land on after sign-in / app open, e.g. "/" or "/transactions". */
  defaultLandingPage: string;
  /** "full" shows charts + widgets; "compact" shows stat cards + widgets only. */
  dashboardLayout: "full" | "compact";
  displayName?: string;
  email?: string;
}

/* ---- Derived view-models (computed, never stored) ---- */

/** Planned vs actual for one category in a month. */
export interface CategorySummary {
  category: Category;
  planned: number;
  actual: number;
  remaining: number;
  utilization: number; // 0..n (1 = 100%)
  status: "safe" | "warning" | "over";
  transactionCount: number;
  /** Whether daily-pace tracking is on for this category. */
  paceEnabled: boolean;
  /** Days remaining in the month — only for the current month, else null. */
  daysLeft: number | null;
  /** Remaining budget ÷ days left — null when not applicable. */
  safeDailySpend: number | null;
}

/** Derived (never stored) progress of one EMI as of "today". */
export interface EmiProgress {
  emi: Emi;
  paidInstallments: number;
  remainingInstallments: number;
  paidAmount: number;
  remainingAmount: number;
  totalAmount: number;
  /** Next installment date, or null when completed/stopped. */
  nextPaymentDate: string | null;
  isCompleted: boolean;
}

/** Derived split of expenses into EMI vs non-EMI. */
export interface EmiSplit {
  emiTotal: number;
  nonEmiTotal: number;
  total: number;
  emiShare: number; // 0..1
}

/** Derived stats for one credit card's current statement cycle. */
export interface CardCycleStats {
  card: CreditCard;
  cycleStart: string;
  cycleEnd: string;
  cycleSpend: number;
  monthSpend: number;
  utilization: number; // 0..n of creditLimit
  transactionCount: number;
}

export interface MonthSummary {
  monthKey: MonthKey;
  income: number;
  plannedExpenses: number;
  actualExpenses: number;
  emergencyFundSaved: number;
  sipInvested: number;
  remainingBalance: number;
  savingsRate: number; // share of income not spent; negative on a deficit
  budgetUtilization: number; // 0..1 (actual / planned)
}
